package com.mygdx.game;

import com.badlogic.gdx.math.MathUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents either a party member or an enemy dependant on AgentType.
 */

//Agent is either an enemy or a party member
public class Agent implements Comparable<Agent>{

    private String name;
    public  AgentType type;//Type of agent this is, either ENEMY or FRIENDLY

    private Statistics stats; //Uses Statistics class to store statistics

    private List<Integer> skills; //Stores IDs of skills this agent can use
    private CurrentEquipment equipment;    //Stores IDs of equipment the agent currently has equipped

    private float x,y;

    private int texture;

    /**
     * Whether or not this Agent is currently attacking.
     */
    private boolean attacking;

    /**
     * The time that the Agent has spent on the current attack.
     */
    private float attackTime = 0;


    /**
     * Implements the compareTo function required when implementing the Comparable abstract class.
    * Compares the total speeds of two agents, using base stats and equipment modifiers.
    * Orders in descending order.
    */
    public int compareTo(Agent agent){

        int thisSpeed = this.stats.getSpeed()+this.getCurrentEquipment().getTotalSpeedModifiers();
        int otherSpeed = agent.getStats().getSpeed() + agent.getCurrentEquipment().getTotalSpeedModifiers();
        return otherSpeed-thisSpeed;
    }

    /**
     * @param name the name of the Agent.
     * @param type defines whether a friendly or enemy.
     * @param stats an instance of {@link Statistics}.
     * @param skills a list of skill ID's that the agent can use.
     * @param equipment an instance of {@link CurrentEquipment}.
     */
    public Agent(String name, AgentType type, Statistics stats, List<Integer> skills, CurrentEquipment equipment, int texture){

        this.name = name;
        this.type = type;
        this.stats = stats;
        this.skills = skills;
        this.equipment = equipment;
        this.x=0;
        this.y=0;
        this.texture = texture;
    }
    /**
     * Empty constructor required for class to be generated by deserialising json.
     */
    public Agent(){};

    public void healFull(int power){
        stats.increaseHP(stats.getMaxHP());
        stats.increaseMP(stats.getMaxMP());
    }

    public int dealDamage(int power, Agent attacker){
        // Calculate chance to take damage based on attacker's and defender's dexterity.
        float hitChance = MathUtils.clamp(1 - ((float) getTotalDexterity() / attacker.getTotalDexterity()) / 10, 0.1f, 0.9f);

        // DEBUG
        System.out.println(hitChance);

        int damageDone = 0;

        if(hitChance > MathUtils.random()) {
            float multiplier = (float) MathUtils.clamp(Math.sqrt((float) attacker.getTotalStrength() / getTotalDefence()), 0.1, 1);
            damageDone = MathUtils.round(power * multiplier);

            System.out.println("DAMAGE DONE " + damageDone);
            System.out.println("DAMAGE CALC " + multiplier);

            stats.reduceHP(damageDone);
        }



        // Return the actual damage done.
        return damageDone;
    }
    public void dealHealth(int amount){
        stats.increaseHP(amount);
    }

    public void giveMana(int amount){
    	stats.increaseMP(amount);
    }

    public void takeMana(int amount){
    	stats.reduceMP(amount);
    }

    public Statistics getStats() {
        return this.stats;
    }

    public enum AgentType{
        ENEMY,FRIENDLY
    }


    public CurrentEquipment getCurrentEquipment() {
        return equipment;
    }
    //////////////
    //Need to work out how adding equipment when creating agent will work with the armour value statistics of the agent
    /////////////

    /////////
    //Skills
    /////////
    public void addSkill(int skillID){
        if(skills.size()>0){
            if(!skills.contains(skillID)){
                skills.add(skillID);
            }
        }
        else{
            skills.add(skillID);
        }

    }

    public List<Integer> getSkills() {
    	List<Integer> tempSkills = new ArrayList<Integer>();
    	if(this.getStats().getCurrentLevel() >= 8 && skills.size() >= 4) {
    		tempSkills.add(skills.get(3));
    	}
    	if(this.getStats().getCurrentLevel() >= 4 && skills.size() >= 3) {
    		tempSkills.add(skills.get(2));
    	}
    	if(this.getStats().getCurrentLevel() >= 2 && skills.size() >= 2) {
    		tempSkills.add(skills.get(1));
    	}
		tempSkills.add(skills.get(0));
        return tempSkills;
    }

    
//	TOTAL means sum of base and equipment modifiers
    
    public int getTotalSpeed(){
    	return this.getStats().getSpeed()+this.getCurrentEquipment().getTotalSpeedModifiers();
    }
    
    public int getTotalStrength(){
    	return this.getStats().getStrength() + this.getCurrentEquipment().getTotalStrengthModifiers();
    }
    
    public int getTotalDexterity(){
    	return this.getStats().getDexterity()+this.getCurrentEquipment().getTotalDexterityModifiers();
    }
    
    public int getTotalInteligence(){
    	return this.getStats().getIntelligence()+this.getCurrentEquipment().getTotalIntelligenceModifiers();
    }
    
    public int getTotalDefence(){
    	return this.getStats().getArmourVal()+this.getCurrentEquipment().getTotalArmourValModifiers();
    }


    public String getName() {
        return name;
    }

    public boolean isDead(){
        if(stats.getCurrentHP()<=0)
            return true;
        else
            return false;
    }

    public AgentType getType() {
        return type;
    }

    public float getX() {
        return x;
    }

    public void setX(float x) {
        this.x = x;
    }

    public float getY() {
        return y;
    }

    public void setY(float y) {
        this.y = y;
    }

    public boolean isAttacking() {
        return attacking;
    }

    public void setAttacking(boolean attacking) {
        this.attacking = attacking;

        if(!attacking) {
            attackTime = 0;
        }
    }

    public float getAttackTime() {
        return attackTime;
    }

    public void updateAttackTime(float delta) {
        this.attackTime += delta;
    }

    @Override
    public String toString() {
        return "Agent{" +
                "name='" + name + '\'' +
                ", type=" + type +
                ", stats=" + stats +
                ", skills=" + skills +
                ", equipment=" + equipment +
                '}';
    }

    public int getTexture() {
        return texture;
    }

}
