package com.mygdx.game;

public class Consumable{

    private int ID = -1;
    private String name, description;
    private ConsumeType type;
    private int power;
    private int cost;

    public Consumable(String name, String description, ConsumeType type, int power, int cost) {
        this.name = name;
        this.description = description;
        this.type = type;
        this.power = power;
        this.cost = cost;
    }
    /**
     * Empty constructor required for class to be generated by deserialising json.
     */
    public Consumable(){}


    public void updateID(int id) {
        this.ID = id;
    }

    public enum ConsumeType {
        HEAL, REVIVE, MANAHEAL, SPEEDBUFF, STRENGTHBUFF, DEXTERITYBUFF, INTELLIGENCEBUFF;
    }


    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public ConsumeType getType() {
        return type;
    }

    public int getPower() {
        return power;
    }
    
    public int getID() {
        return ID;
    }

    public int getCost() {
        return cost;
    }

    @Override
    public String toString() {
        return "Consumable{" +
                "ID=" + ID +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", type=" + type +
                ", power=" + power +
                '}';
    }
}
