package com.mygdx.game;

import java.util.List;

import com.badlogic.gdx.utils.Json;
import com.badlogic.gdx.utils.JsonValue;
import com.mygdx.game.Agent.AgentType;


/**
 * An individual shop, instantiated and stored in the ShopManager.
 * Implements Json.Serializable to allow objects to be easily generated.
 */
public class Shop{

	private int ID;
    private List<Integer> equipment;
    private List<Integer> consumables;
    private List<Integer> consumablesQuantity;


    public Shop(List<Integer> equipment, List<Integer> consumables, List<Integer> consumablesQuantity) {
        this.equipment = equipment;
        this.consumables = consumables;
        this.consumablesQuantity = consumablesQuantity;
    }

    /**
     * Empty constructor required for class to be generated by deserialising json.
     */
    public Shop(){}

    public void updateID(int id){
        this.ID = id;
    }

    public int getID() {
        return ID;
    }
    
    public List<Integer> getEquipment() {
        return equipment;
    }
    
    public List<Integer> getConsumables() {
        return consumables;
    }
    
    public List<Integer> getConsumablesQuantity() {
        return consumablesQuantity;
    }
}
