package com.mygdx.game;

import java.util.Random;

/**
 * Stores an agents statistics.
 */

public class Statistics {
	
	private final int[] LEVEL_CURVE = {10, 20, 35, 50, 70, 95, 125, 160, 200, 250};

    private int currentHP,currentMP, maxHP, maxMP;
    private int speed,strength,dexterity,intelligence;
    private int baseArmourVal,armourVal;
    private int experience, currentLevel;
    public final int maxLevel = 10;
    public final int maxExp = 250;


    @Override
    public String toString() {
        return "Statistics{" +
                "currentHP=" + currentHP +
                ", currentMP=" + currentMP +
                ", maxHP=" + maxHP +
                ", maxMP=" + maxMP +
                ", speed=" + speed +
                ", strength=" + strength +
                ", dexterity=" + dexterity +
                ", intelligence=" + intelligence +
                ", baseArmourVal=" + baseArmourVal +
                ", armourVal=" + armourVal +
                ", experience=" + experience +
                ", currentLevel=" + currentLevel +
                ", maxLevel=" + maxLevel +
                '}';
    }

    public Statistics(int maxHP, int maxMP, int speed, int strength, int dexterity, int intelligence, int baseArmourVal, int experience, int currentLevel) {
        this.maxHP = maxHP;
        this.maxMP = maxMP;
        this.currentHP = maxHP; //Current HP & MP set to max
        this.currentMP = maxMP;

        this.speed = speed; //Determines turn order
        this.strength = strength; //Determines melee damage
        this.dexterity = dexterity; //Determines ranged damage
        this.intelligence = intelligence; //Determines magic damage

        this.baseArmourVal = baseArmourVal; //influenced by armour
        this.armourVal = baseArmourVal;

        this.experience = experience; //current amount of xp
        this.currentLevel = currentLevel;

    }
    /**
     * Empty constructor required for class to be generated by deserialising json.
     */
    public  Statistics(){};

    public int increaseXP(int xp){//might need to return things when level up
        int levelIncrease = 0;
        Random random = new Random();
        experience+=xp;
        while(experience>=this.getLevelCap()) {
        	maxHP += random.nextInt(intelligence*10) + 10;
        	currentHP = maxHP;
        	maxMP += random.nextInt(intelligence) + 1;
        	currentMP = maxMP;
        	speed += random.nextInt(intelligence) + 1;
        	strength += random.nextInt(intelligence) + 1;
        	dexterity += random.nextInt(intelligence) + 1;
        	intelligence += random.nextInt(intelligence) + 1;
        	
            currentLevel += 1;
            levelIncrease+=1;
        }
        if(levelIncrease>0)
            return levelIncrease;
        else
            return -1;
    }

    //when equipment is changed, this should be called
    public void adjustArmourVal() {

    }


    public void reduceHP(int amount){
        currentHP-=amount;
        if(currentHP<0){
            currentHP=0;
        }
    }
    public void increaseHP(int amount){
        currentHP+=amount;
        if(currentHP>maxHP)
            currentHP=maxHP;
    }

    public void increaseMP(int amount){
        currentMP+=amount;
        if(currentMP>maxMP)
            currentMP=maxMP;
    }

    public void reduceMP(int amount){
        currentMP-=amount;
        if(currentMP<0)
            currentMP=0;
    }

    /////////////
    //Get Methods
    /////////////
    public int[] getAllStats(){
        int[] x = {currentHP,currentMP,maxHP, maxMP,speed,strength,dexterity,intelligence,baseArmourVal,armourVal,experience, currentLevel};
        return x;
    }

    public int getCurrentHP() {
        return currentHP;
    }

    public int getCurrentMP() {
        return currentMP;
    }

    public int getMaxHP() {
        return maxHP;
    }

    public int getMaxMP() {
        return maxMP;
    }

    public int getSpeed() {
        return speed;
    }

    public int getStrength() {
        return strength;
    }

    public int getDexterity() {
        return dexterity;
    }

    public int getIntelligence() {
        return intelligence;
    }

    public int getBaseArmourVal() {
        return baseArmourVal;
    }

    public int getArmourVal() {
        return armourVal;
    }

    public int getExperience() {
        return experience;
    }

    public int getCurrentLevel() {
        return currentLevel;
    }

    public int getLevelCap() { return LEVEL_CURVE[this.getCurrentLevel()]; }
    
    public int getMaxExP() {return maxExp;}
}
